[platformio]
default_envs = esp32doit-devkit-v1

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_flags =
  -D SIGAS_RT_ENV_TEST
extra_scripts =
  post:simulation/merge_firmware.py
lib_deps =
  madhephaestus/ESP32Servo@^3.0.9

[env:esp32doit-devkit-v1-diagnostic-load]
extends = env:esp32doit-devkit-v1
build_flags =
  -D SIGAS_RT_ENV_TEST
  -D SIGAS_RT_DIAGNOSTICS_LOAD

[env:esp32doit-devkit-v1-sensor-timeout-test]
extends = env:esp32doit-devkit-v1
build_flags =
  -D SIGAS_RT_ENV_TEST
  -D SIGAS_RT_SENSOR_TIMEOUT_TEST

[env:esp32doit-devkit-v1-initial-sensor-timeout-test]
extends = env:esp32doit-devkit-v1
build_flags =
  -D SIGAS_RT_ENV_TEST
  -D SIGAS_RT_INITIAL_SENSOR_TIMEOUT_TEST

[env:esp32doit-devkit-v1-visualization]
extends = env:esp32doit-devkit-v1
build_flags =
  -D SIGAS_RT_ENV_TEST
  -D SIGAS_RT_VISUALIZATION

[env:esp32doit-devkit-v1-visualization-sensor-timeout-test]
extends = env:esp32doit-devkit-v1
build_flags =
  -D SIGAS_RT_ENV_TEST
  -D SIGAS_RT_VISUALIZATION
  -D SIGAS_RT_SENSOR_TIMEOUT_TEST

[env:esp32doit-devkit-v1-visualization-initial-sensor-timeout-test]
extends = env:esp32doit-devkit-v1
build_flags =
  -D SIGAS_RT_ENV_TEST
  -D SIGAS_RT_VISUALIZATION
  -D SIGAS_RT_INITIAL_SENSOR_TIMEOUT_TEST
